### ISSUE TITLE
Plain text Post api return wrong file id if the file is duplicates

### ISSUE THREAD

**Issue by jessejiang0214** [tagtog/tagtog-doc#6]
My use case is I try to upload all files in local as a text so I call Post api, If the text already exists in the project Post API return this to me 

```{"ok":0,"errors":1,"items":[{"origid":"text","names":["text.txt"],"rawInputSizeInBytes":2115,"error":{"reason":"duplicated","msg":"duplicates hiFp5Kqfg7Pu7CIIMtvGl2hGzLG-*"}}],"warnings":["These documents are duplicates (the existing documents were not replaced): text (duplicates hiFp5Kqfg7Pu7CIIMtvGl2hGzLG-*)"]}```

Which is ok, but the ```duplicates hiFp5Kqfg7Pu7CIIMtvGl2hGzLG-*``` I want i should be the file id like ```ahiFp5Kqfg7Pu7CIIMtvGl2hGzLG-text```, So this is the bug or some feature by design?

**Comment by juanmirocks** [comment]
Thanks for the report @jessejiang0214 

It is a feature by design. They key part of the id is `hiFp5Kqfg7Pu7CIIMtvGl2hGzLG`. This is a hash we generate out of the document's text. We check this hash to compare whether two documents, regardless of their name, or minor spacing differences, do contain the same text, and are therefore duplicates.

Hope that makes sense.

I'm happy to know your intended use case of labeling data. PM me at info@tagtog.net

CC @jorgecoa
